export default {
    // Search Tabs
    tabs: {
        organic: 'Organic Molecules',
        inorganic: 'Inorganic Molecules',
        third: 'Solid-State Electrolyte'
    },
    
    // Search Input
    searchPlaceholder: "Enter SMILES string(s), molecule name(s), or property query",
    searchButton: "Search",
    searchTooltip: '<p>Valid queries can search over any numerical properties of molecules. For example:</p><p>- "Find all molecules with HOMO at most -8"<br/>- "Find all molecules with LUMO at least -2 and molecular weight at most 200"</p><p>For more open-ended queries, use Ask.</p><p>To draw and look up SMILES strings, please click this icon or visit <a>{{pubChemUrl}}</a></p>',
    drawMolecule: "Draw molecule",
    
    // Search Options
    findFriendsLabel: 'Find "friends"',
    findFriendsDescription: 'Molecules with similar structures to your input molecules and physicochemical properties that are theoretically compatible with the following battery use case:',

    searchRange: 'Search range',
    nearbyFriends: 'nearby friends',
    distantFriends: 'distant friends',
    advancedOptions: 'Advanced options',
    intelligentCompute: 'Intelligent find-a-friend compute',
    showHypothetical: 'Show hypothetical molecules',
    showHypotheticalTooltip: "Include candidates generated by our algorithm that aren’t in public catalogs; availability and synthesizability are uncertain.",
    computeDisabled: 'Disabled',
    computeLow: 'Low',
    computeMedium: 'Medium',
    computeHigh: 'High',
    computeExtreme: 'Extreme',
    cathode: 'Cathode',
    anode: 'Anode',
    salt: 'Salt',
    solvent: 'Primary Solvent',
    performanceMetric: 'Desired Performance Metric',
    extraRequests: 'Custom molecule constraints (for best results, enable Intelligent Find-a-Friend):',
    extraRequestsPlaceholder: 'Display only molecules with Ether functional groups.',
    custom: 'Custom',
    upgradeEnterprise: 'Upgrade to an enterprise-tier account',
    upgradeAccount: 'Upgrade your account',
    computeWarning: 'Additional context is necessary for high performance of Intelligent find-a-friend. Compute power has been set to Low.',
    
    // Loading and Status Messages
    searching: "Searching...",
    loadingMap: "Loading Map of the Molecular Universe",
    errorLoadingData: "Error loading data",
    noDataAvailable: "No data available",
    tooManyRequests: "Too many requests. Please wait a moment before trying again.",
    
    // Search Results
    searchedMolecules: "Searched Molecules",
    moleculeNumber: "Molecule {{number}}",
    similarMolecules: "Similar Molecules",
    similarMoleculeNumber: "Similar Molecule #{{number}}",
    selectMolType: "Select what type of molecule it is for best results",
    
    // Property Names (Professional terms - not translated according to rules)
    properties: {
        smiles: "SMILES",
        chemicalFormula: "Chemical Formula",
        molecularWeight: "Molecular Weight",
        homo: "HOMO",
        lumo: "LUMO",
        espMin: "ESP Min",
        espMax: "ESP Max",
        predictedMp: "Predicted Melting Point",
        predictedBp: "Predicted Boiling Point",
        predictedFp: "Predicted Flash Point",
        combustionEnthalpy: "Combustion Enthalpy",
        commercialScore: "Commercial Score",
        functionalGroups: "Functional Groups",
        umapX: "UMAP_X",
        umapY: "UMAP_Y"
    },

    moleculeTypes: {
        selectMolType: "Molecule Type",
        solvent: "Solvent",
        cosolvent: "Cosolvent",
        diluent: "Diluent",
        additive: "Additive",
        additiveSubtype: "Additive subcategory",
        additiveOptions: {
            seiPromoter: "SEI Promoter",
            sideReactionSuppressor: "Side reaction suppressor",
            dendriteSuppressor: "Dendrite suppressor",
            interfacialStabilityImprover: "Interfacial stability improver"
        }
    },
    
    // Buttons and Actions
    addToFavorites: "Add to Favorites ★",
    saving: "Saving...",
    
    // Warning and Error Messages
    multipleMoleculesWarning: "Multiple molecules found matching your search criterion. Find friends disabled.",
    findFriendError: "Failed to find similar molecules. Please try again.",
    searchError: "Error searching for molecules. Please try again.",
    
    // Not Found Message
    moleculeNotFound: {
        title: "Your query did not return any molecules. Here are several possibilities:",
        reasons: [
            "Your query may not be battery relevant or have errors. Please check.",
            "Your result molecules are included in premium levels Enterprise and Joint Development. Please upgrade.",
            "Your query hit one of our hidden galaxies of treasure molecules. Please contact us.",
            "Your query might involve salt or anion molecules, which our current database doesn't yet support. We'll be adding anions in an upcoming update."
        ],
        contactSales: "Contact Sales"
    },

    // Ambiguous Query Message
    ambiguousQuery: {
        message: "Your query is ambiguous. The abbreviation {{query}} can correspond to any of the following molecules: {{options}}. Please refine your query."
    }
}; 