export default {
    // Search Tabs
    tabs: {
        organic: 'Solvents, Additives & Diluents',
        inorganic: 'Inorganic Solvent, Additives & Diluents',
        anions: 'Salt Anions',
        third: 'Solid Electrolytes '
    },
    
    // Search Input
    searchPlaceholder: "Enter SMILES string(s), molecule name(s), or property query",
    searchButton: "Search",
    searchTooltip: '<p>Valid queries can search over any numerical properties of molecules. For example:</p><p>- "Find all molecules with HOMO at most -8"<br/>- "Find all molecules with LUMO at least -2 and molecular weight at most 200"</p><p>For more open-ended queries, use Ask.</p><p>To draw and look up SMILES strings, please click this icon or visit <a>{{pubChemUrl}}</a></p>',
    drawMolecule: "Draw molecule",
    importSmilesTooltip: 'Import SMILES to drawing tool.',
    similarityPrompt: 'Search for molecules that are structurally similar to:',
    similarityTooltip: {
        title: 'Search',
        lines: [
            'The Search algorithm will look up your molecules in our database and find similar molecules to them.',
            'Enter a list of any number of molecules by SMILES string, molecule name, or common abbreviation.',
            'Leave this box blank for an unbiased Search.',
            'Click the drawing icon on the left to draw a custom molecule and automatically enter its SMILES string into this box.',
        ],
    },
    propertyConstraints: {
        intro: 'subject to the following property constraints:',
        tooltipTitle: 'Custom property constraints',
        tooltipIntro: 'Search supports a natural-language interface for tuning your Search results based on your desired molecular properties and structure. You can request any of the following:',
        atomCounts: 'Desired atom counts of various elements',
        functionalGroups: 'Desired presence or absence of certain functional groups',
        commercialAvailability: 'Commercial availability',
        valueRangeBullet: 'Value ranges or bounds for {{properties}}.',
    },
    
    // Search Options
    findFriendsLabel: 'intended as:',
    findFriendsDescription: 'Molecules with similar structures to your input molecules and physicochemical properties that are theoretically compatible with the following battery use case:',
    useCaseTooltipTitle: 'SES molecule property optimizer',
    useCaseTooltipDescription: "Enter what type of battery molecule you're looking for, and SES's molecule property optimizer will display results that are more likely to be compatible with your chosen use case.",

    searchRange: 'Search range',
    nearbyFriends: 'nearby friends',
    distantFriends: 'distant friends',
    searchRangeTooltip: 'Drag the slider to the left to prioritize molecules with maximum property compatibility with your use case, regardless of their structure. Drag the slider to the right to prioritize molecules with maximum structural similarity to your input molecules.',
    advancedOptions: 'Advanced options',
    intelligentCompute: 'Intelligent find friends compute',
    intelligentFindFriendsLabel: 'Intelligent Search',
    intelligentFindFriendsTooltip: 'Examine hundreds of molecules with LLMs to find even more relevant molecules to your application. Increase the compute power and fill out the battery system information (under Advanced options) for best results.',
    intelligentFindFriendsLimitLabel: 'Remaining monthly: {{remaining}} / {{limit}}',
    showHypothetical: 'Show hypothetical molecules',
    showHypotheticalTooltip: "Include candidates generated by our algorithm that aren’t in public catalogs; availability and synthesizability are uncertain.",
    computeDisabled: 'Disabled',
    computeLow: 'Low',
    computeMedium: 'Medium',
    computeHigh: 'High',
    computeExtreme: 'Extreme',
    cathode: 'Cathode',
    anode: 'Anode',
    solvent: 'Electrolyte formulation',
    cellDesign: 'Cell design',
    performanceMetric: 'Desired Performance Metric',
    extraRequests: 'Custom molecule constraints (for best results, enable Intelligent Find Friends):',
    extraRequestsPlaceholder: 'Display only molecules with Ether functional groups.',
    custom: 'Custom',
    upgradeEnterprise: 'Upgrade to an enterprise-tier account',
    upgradeAccount: 'Upgrade your account',
    computeWarning: 'Additional context is necessary for high performance of Intelligent find friends. Compute power has been set to Low.',
    batteryInfoRecommendation: 'Recommended battery information to help intelligent find friends find the most relevant molecules for you: Cathode, Anode, Electrolyte formulation, Cell design, Desired performance metric.',
    
    searchRange: 'Search range',
    nearbyFriends: 'nearby friends',
    distantFriends: 'distant friends',
    advancedOptions: 'Advanced options',
    intelligentCompute: 'Intelligent find friends compute',
    computeDisabled: 'Disabled',
    computeLow: 'Low',
    computeMedium: 'Medium',
    computeHigh: 'High',
    computeExtreme: 'Extreme',
    cathode: 'Cathode',
    anode: 'Anode',
    solvent: 'Electrolyte formulation',
    cellDesign: 'Cell design',
    performanceMetric: 'Desired Performance Metric',
    extraRequests: 'Custom molecule constraints (for best results, enable Intelligent Find Friends):',
    extraRequestsPlaceholder: 'Display only molecules with Ether functional groups.',
    custom: 'Custom',
    upgradeEnterprise: 'Upgrade to an enterprise-tier account',
    upgradeAccount: 'Upgrade your account',
    computeWarning: 'Additional context is necessary for high performance of Intelligent find friends. Compute power has been set to Low.',

    // Loading and Status Messages
    searching: "Searching...",
    loadingMap: "Loading Map of the Molecular Universe",
    errorLoadingData: "Error loading data",
    noDataAvailable: "No data available",
    tooManyRequests: "Too many requests. Please wait a moment before trying again.",
    
    // Search Results
    searchedMolecules: "Searched Molecules",
    moleculeNumber: "Molecule {{number}}",
    similarMolecules: "Recommended Molecules",
    similarMoleculeNumber: "Similar Molecule #{{number}}",
    selectMolType: "Select what type of molecule it is for best results",
    
    // Property Names (Professional terms - not translated according to rules)
    properties: {
        smiles: "SMILES",
        casrn: "CAS #",
        chemicalFormula: "Chemical Formula",
        molecularWeight: "Molecular Weight",
        overallScore: "Overall Score",
        homo: "HOMO",
        lumo: "LUMO",
        espMin: "ESP Min",
        espMax: "ESP Max",
        molecularVolume: "Molecular Volume",
        fluorideBondDissociationEnergy: "F Bond Dissociation Energy",
        predictedMp: "Predicted Melting Point",
        predictedBp: "Predicted Boiling Point",
        predictedFp: "Predicted Flash Point",
        combustionEnthalpy: "Combustion Enthalpy",
        commercialScore: "Commercial Score",
        functionalGroups: "Functional Groups",
        umapX: "UMAP_X",
        umapY: "UMAP_Y"
    },

    moleculeTypes: {
        selectMolType: "Molecule Type",
        solvent: "Solvent",
        cosolvent: "Cosolvent",
        diluent: "Diluent",
        primarySalt: "Primary Salt",
        additive: "Additive",
        additiveSubtype: "Additive subcategory",
        additiveCategory: "Category",
        additiveCategories: {
            mechanistic: "Mechanistic",
            outcome: "Outcome",
            mechanisticOptions: {
                seiStabilizer: "SEI Stabilizer",
                ceiStabilizer: "CEI Stabilizer",
                hfNeutralizer: "HF Neutralizer",
                tmDissolutionSuppressor: "TM Dissolution Suppressor",
                desolvationOptimizer: "Desolvation Optimizer",
                dendriteSuppressor: "Dendrite suppressor",
                polysulfideSuppressor: "Polysulfide suppressor",
                gasSuppressor: "Gas suppressor",
                flameRetardant: "Flame retardant"
            },
            outcomeOptions: {
                fastCharging: "Fast charging",
                highVoltage: "High voltage",
                hotboxThermal: "Inflammability",
                htCycling: "High temp cycling",
                htStorage: "High temp storage",
                ltCycling: "Low temp cycling",
                rtCycling: "Room temp cycling"
            }
        }
    },
    
    // Buttons and Actions
    addToFavorites: "Add to Favorites ★",
    saving: "Saving...",

    // Favorites
    favorites: {
        favorites: "Favorites",
        goToFavorites: "Go to Favorites page"
    },
    
    // Warning and Error Messages
    multipleMoleculesWarning: "Multiple molecules found matching your search criterion. Find friends disabled.",
    findFriendError: "Failed to find similar molecules. Please try again.",
    searchError: "Error searching for molecules. Please try again.",
    
    // Not Found Message
    moleculeNotFound: {
        title: "Your query did not return any molecules. Here are several possibilities:",
        reasons: [
            "Your query may not be battery relevant or have errors. Please check.",
            "Your result molecules are included in premium levels Enterprise and Joint Development. Please upgrade.",
            "Your query hit one of our hidden galaxies of treasure molecules. Please contact us.",
            "Your query might involve salt or anion molecules, which our current database doesn't yet support. We'll be adding anions in an upcoming update."
        ],
        contactSales: "Contact Sales"
    },

    // Ambiguous Query Message
    ambiguousQuery: {
        message: "Your query is ambiguous. The abbreviation {{query}} can correspond to any of the following molecules: {{options}}. Please refine your query."
    }
}; 
