server{
    listen        80;
    server_name   localhost;
    add_header Access-Control-Allow-Origin '*';
    gzip on;  			  #开启gzip功能
    gzip_types *;		  #压缩源文件类型,根据具体的访问资源类型设定
    gzip_comp_level 6;	  #gzip压缩级别
    gzip_min_length 1024; #进行压缩响应页面的最小长度,content-length
    gzip_buffers 4 16K;	  #缓存空间大小
    gzip_http_version 1.1; #指定压缩响应所需要的最低HTTP请求版本
    gzip_vary  on;		  #往头信息中添加压缩标识
    gzip_disable "MSIE [1-6]\."; #对IE6以下的版本都不进行压缩

    location /{
        expires  10m;
        root /usr/share/nginx/html;
        try_files $uri $uri/index.html /index.html;
        index index.html index.htm;
    }

    error_page  500 502 503 504  /50x.html;
    location = 50x.html{
        root /usr/share/nginx/html;
    }
}