import type { EndpointConfig } from './types';

/**
 * Endpoint map for legacy authFetch usage.
 * - default: common paths
 * - box: overrides paths that differ in box env
 */
export const AUTO_FETCH_ENDPOINTS: EndpointConfig<Record<string, string>> = {
  default: {
    search: '/api/search/search-new',
    sseSearch: '/api/search/sse/search',
    snowflakeQuery: '/api/search/snowflake-query',
    favorites: '/api/user/favorites',
    favoritesRetrieve: '/api/user/favorites-retrieve',
    favoritesDelete: '/api/user/favorites-delete',
    moleculeImage: '/api/search/molecule_image',
    queryLimit: '/api/user/query_limit',
    chatHistory: '/chat-history',
    chatHistoryDetail: '/chat-history',
    chatHistoryDelete: '/chat-history/delete',
    findFriendWithImage: '/api/llm/find-friend-with-image',
    feedback: '/api/feedback',
    moleculeDetails: '/api/molecule_details',
    // Auth
    login: '/api/user/login',
    register: '/api/user/register',
    resetPassword: '/api/user/reset-password',
    resetPasswordToken: '/api/user/reset-password-token',
    redeemCode: '/api/user/redeem-code',
    verifyToken: '/api/user/verify-token',
    verifyRegisterCode: '/api/user/verify-register-code',
    redeemNew: '/api/user/redeem-new',
    bindEduEmail: '/api/user/bind-edu-email',
    verifyEduCode: '/api/user/verify-edu-code',
    forgotPassword: '/api/user/forgot-password',
    verifyForgotPasswordCode: '/api/user/verify-forgot-password-code',
    contactSales: '/api/user/contact-sales',
  },
  us: {
    search: '/api/search/search-new',
    sseSearch: '/api/search/sse/search',
    snowflakeQuery: '/api/search/snowflake-query',
    favorites: '/api/user/favorites',
    favoritesRetrieve: '/api/user/favorites-retrieve',
    favoritesDelete: '/api/user/favorites-delete',
    moleculeImage: '/api/search/molecule_image',
    queryLimit: '/api/user/query_limit',
    // Auth
    login: '/api/user/login',
    register: '/api/user/register',
    resetPassword: '/api/user/reset-password',
    resetPasswordToken: '/api/user/reset-password-token',
    redeemCode: '/api/user/redeem-code',
    verifyToken: '/api/user/verify-token',
    verifyRegisterCode: '/api/user/verify-register-code',
    redeemNew: '/api/user/redeem-new',
    bindEduEmail: '/api/user/bind-edu-email',
    verifyEduCode: '/api/user/verify-edu-code',
    forgotPassword: '/api/user/forgot-password',
    verifyForgotPasswordCode: '/api/user/verify-forgot-password-code',
    contactSales: '/api/user/contact-sales',
  },
  box: {
    search: '/api/search/search-new',
    sseSearch: '/api/search/sse/search',
    snowflakeQuery: '/api/search/snowflake-query',
    favorites: '/api/user/favorites',
    favoritesRetrieve: '/api/user/favorites-retrieve',
    favoritesDelete: '/api/user/favorites-delete',
    moleculeImage: '/api/search/molecule_image',
    queryLimit: '/api/user/query_limit',
    // Auth
    login: '/api/user/login',
    register: '/api/user/register',
    resetPassword: '/api/user/reset-password',
    resetPasswordToken: '/api/user/reset-password-token',
    redeemCode: '/api/user/redeem-code',
    verifyToken: '/api/user/verify-token',
    verifyRegisterCode: '/api/user/verify-register-code',
    redeemNew: '/api/user/redeem-new',
    bindEduEmail: '/api/user/bind-edu-email',
    verifyEduCode: '/api/user/verify-edu-code',
    forgotPassword: '/api/user/forgot-password',
    verifyForgotPasswordCode: '/api/user/verify-forgot-password-code',
    contactSales: '/api/user/contact-sales',
  },
};
