name: Deploy GitHub Pages

on:
  push:
    branches:
      - staging-with-box
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci --legacy-peer-deps --ignore-scripts --no-audit --no-fund --loglevel=verbose

      - name: Upload npm logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs

      - name: Build for GitHub Pages
        run: |
          npm run build:github

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
